# Generated by Django 4.2.16 on 2024-10-26 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('reportage', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reparation', 'reparation'), ('salaire', 'Salaire'), ('facture eau', 'facture eau'), ('electricite', 'electricite'), ('produit repassage', 'Produit repassage'), ('produit lavage', 'Produit lavage'), ('frais divers', 'frais divers')], max_length=20)),
                ('intitule', models.CharField(max_length=132, null=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantite', models.IntegerField(default=1)),
                ('date_depense', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_delivery_confirmation', models.BooleanField(default=True)),
                ('use_partial_payment', models.BooleanField(default=True)),
                ('use_antidate', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.PositiveIntegerField(null=True, unique=True)),
                ('customer', models.CharField(max_length=132, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=132)),
                ('invoice_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.CharField(max_length=132, null=True)),
                ('designation', models.CharField(max_length=132, null=True)),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('wave', 'Wave'), ('om', 'Orange Money'), ('cash', 'Espèces')], max_length=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fact_app.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_services', to='fact_app.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Inpute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titres', models.CharField(max_length=132, null=True)),
                ('montants', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('mode_paiement', models.CharField(blank=True, choices=[('wave', 'Wave'), ('om', 'Orange Money'), ('cash', 'Espèces')], max_length=10, null=True)),
                ('created_ats', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('save_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=132, null=True)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('type_depense', models.CharField(blank=True, choices=[('', 'Retrait'), ('reparation', 'Réparation'), ('salaire', 'Salaire'), ('facture eau', 'Facture eau'), ('electricite', 'Électricité'), ('produit repassage', 'Produit repassage'), ('produit lavage', 'Produit lavage'), ('frais divers', 'Frais divers')], max_length=20, null=True)),
                ('save_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
