name: CI Pipeline pour Tests Selenium

# Événements qui déclenchent le pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Tâches à exécuter
jobs:
  test:
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Configurer Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Installer Chrome et Chromedriver
      - name: Installer Chrome et Chromedriver
        uses: nanasess/setup-chromedriver@v2

      # Étape 5 : Lancer le serveur Django en arrière-plan
      - name: Démarrer le serveur Django
        run: |
          python manage.py runserver &
          sleep 5  # Attendre que le serveur démarre

      # Étape 6 : Exécuter les tests Selenium
      - name: Exécuter les tests
        run: |
          python tests/test_invoice.py